version: '3.8'
services:
  prefect:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      PREFECT_HOME: /data
      PREFECT_EXPERIMENTAL_ENABLE_TASK_SCHEDULING: True
    command: prefect server start --host 0.0.0.0
    ports:
      - "14201:4200"
    volumes:
      - prefect-data:/data
      - .:/app
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      PYTHONUNBUFFERED: 1
      PREFECT_API_URL: http://prefect:4200/api
      PREFECT_LOCAL_STORAGE_PATH: /task-storage
      PREFECT_EXPERIMENTAL_ENABLE_TASK_SCHEDULING: True
    command: flask --app flask_task_monitoring.api run --host 0.0.0.0 --port 8001 --debug
    ports:
      - 8001:8001
    volumes:
      - task-storage:/task-storage
      - .:/app
    depends_on:
      - prefect
  tasks:
    deploy:
      replicas: 2
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      PREFECT_API_URL: http://prefect:4200/api
      PREFECT_LOCAL_STORAGE_PATH: /task-storage
      PREFECT_EXPERIMENTAL_ENABLE_TASK_SCHEDULING: True
    env_file:
      - .openai.env
    command: python -m flask_task_monitoring.tasks
    volumes:
      - task-storage:/task-storage
      - .:/app
    depends_on:
      - prefect
  tests:
    deploy:
      replicas: 0
    build:
      context: .
      dockerfile: Dockerfile
      target: testing
    entrypoint: pytest tests --asyncio-mode=auto
    volumes:
      - .:/app
volumes:
  prefect-data: {}
  task-storage: {}
