#!/bin/bash
set -e
PYTHON=3.12.1

pyenv install $PYTHON -s

for directory in $(ls -d */); do
    name=${directory%?}
    cd $directory
    pyenv virtualenv $PYTHON tse-$name || true
    pyenv local tse-$name
    cd ..
done
