version: '3.8'
services:
  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
  mailboi:
    image: thiht/smocker
    environment:
      SMOCKER_MOCK_SERVER_LISTEN_PORT: "80"
    ports:
      # smocker's UI
      - 18888:8081
  marketito:
    image: thiht/smocker
    environment:
      SMOCKER_MOCK_SERVER_LISTEN_PORT: "80"
    ports:
      # smocker's UI
      - 18889:8081
  prefect:
    environment:
      PREFECT_LOCAL_STORAGE_PATH: /data
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
    volumes:
      - prefect-data:/data
      - .:/app
      - ../../prefect/:/prefect
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      PREFECT_API_URL: http://prefect:4200/api
      PREFECT_LOCAL_STORAGE_PATH: /data
    command: python -m fastapi_user_signups
    ports:
      - 8000:8000
    volumes:
      - prefect-data:/data
      - .:/app
      - ../../prefect/:/prefect
    depends_on:
      - prefect
      - redis
      - mailboi
      - marketito
  tasks:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      PREFECT_API_URL: http://prefect:4200/api
      PREFECT_LOCAL_STORAGE_PATH: /data
    command: python -m fastapi_user_signups.tasks
    volumes:
      - .:/app
      - ../../prefect/:/prefect
      - prefect-data:/data
    depends_on:
      - prefect
      - redis
      - mailboi
      - marketito
  tests:
    deploy:
      replicas: 0
    build:
      context: .
      dockerfile: Dockerfile
      target: testing
    environment:
      PREFECT_API_URL: http://prefect:4200/api
    entrypoint: pytest tests
    volumes:
      - .:/app
      - ../../prefect/:/prefect
    depends_on:
      - redis
      - mailboi
      - marketito
volumes:
  prefect-data: {}
  redis-data: {}
