version: '3.8'
services:
  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
  mailboi:
    image: thiht/smocker
    environment:
      SMOCKER_MOCK_SERVER_LISTEN_PORT: "80"
    ports:
      - 18888:8081
  marketito:
    image: thiht/smocker
    environment:
      SMOCKER_MOCK_SERVER_LISTEN_PORT: "80"
    ports:
      - 18889:8081
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    command: python -m fastapi_user_signups
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - ../../prefect/src/prefect:/usr/local/lib/python3.12/site-packages/prefect
    depends_on:
      - redis
      - mailboi
      - marketito
  tests:
    deploy:
      replicas: 0
    build:
      context: .
      dockerfile: Dockerfile
      target: testing
    entrypoint: pytest tests
    volumes:
      - .:/app
      - ../../prefect/src/prefect:/usr/local/lib/python3.12/site-packages/prefect
    depends_on:
      - redis
      - mailboi
      - marketito
volumes:
  redis-data: {}
