[project]
name = "minimal-docker-compose"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["prefect"]

[dependency-groups]
dev = ["ruff"]

[tool.ruff.lint]
extend-select = ["I", "E", "UP"]
