services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prefect
    volumes:
      - postgres-data:/var/lib/postgresql/data
  prefect:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      PREFECT_HOME: /data
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://prefect:password@postgres/prefect
    command: prefect server start --host 0.0.0.0
    ports:
      - "14202:4200"
    volumes:
      - prefect-data:/data
      - .:/app
    depends_on:
      - postgres
  tasks:
    deploy:
      replicas: 8
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      PREFECT_API_URL: http://prefect:4200/api
      PREFECT_LOCAL_STORAGE_PATH: /task-storage
    command: python -m chaos_duck.tasks
    volumes:
      - task-storage:/task-storage
      - .:/app
    depends_on:
      - prefect
  duck:
    deploy:
      replicas: 0
    restart: no
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      PREFECT_API_URL: http://prefect:4200/api
      PREFECT_LOCAL_STORAGE_PATH: /task-storage
    entrypoint: python -m chaos_duck
    volumes:
      # Allows for some Docker-in-Docker operations to sow chaos
      - /var/run/docker.sock:/var/run/docker.sock
      - task-storage:/task-storage
      - .:/app
    depends_on:
      - prefect
volumes:
  postgres-data: {}
  prefect-data: {}
  task-storage: {}
